```{r}
here::i_am("trabalhoMineracao/classificacao.Rmd")
library(here)
library(tidyverse)
library(janitor)
library(lubridate)


tabela_despesa_publica2 <- read_csv2("despesasFormatado.csv")
tabela_despesa_publica2$`Valor Recebido`[tabela_despesa_publica2$`Valor Recebido` == 0] <- 1
```
Dados obitidos 
https://www.portaltransparencia.gov.br/despesas/recursos-recebidos?paginacaoSimples=true&tamanhoPagina=&offset=&direcaoOrdenacao=asc&de=01%2F07%2F2022&ate=30%2F09%2F2022&uf=MG&nomeMunicipio=Uberl%C3%A2ndia&colunasSelecionadas=linkDetalhamento%2CmesAno%2Cfavorecido%2CtipoFavorecido%2CufFavorecido%2CmunicipioFavorecido%2CvalorRecebido&ordenarPor=mesAno&direcao=asc


VER GRAFIO GGPLOT GEOM_HISTOGRAM E BAR


```{r}
library(ggplot2)

figura <- ggplot(tabela_despesa_publica2, aes(`Tipo de Favorecido`))
figura <- figura + geom_bar()
figura

summary(tabela_despesa_publica2$`Tipo de Favorecido`)

```

Utilizando o Rpart para prever o valor das Receitas

```{r}
length(tabela_despesa_publica2$`Tipo de Favorecido`)

tabela_despesa_publica2$cnpj_cpf <- as.factor(tabela_despesa_publica2$cnpj_cpf)
tabela_despesa_publica2$nome <- as.factor(tabela_despesa_publica2$nome)
tabela_despesa_publica2$`Tipo de Favorecido` <- as.factor(tabela_despesa_publica2$`Tipo de Favorecido`)

linhas <- sample(1:length(tabela_despesa_publica2$`Tipo de Favorecido`),length(tabela_despesa_publica2$`Tipo de Favorecido`)*0.7)
```

70%
```{r}
treino <- tabela_despesa_publica2[linhas,]
```
30%
```{r}
teste <- tabela_despesa_publica2[-linhas,]

length(teste$`Tipo de Favorecido`) + length(treino$`Tipo de Favorecido`)
```

Criar o modelo
```{r}
library(rpart)
modelo <- rpart(`Valor Recebido` ~., data=treino, control=rpart.control(cp=0))
```

Realizar previsoes

predict
```{r}
teste$Previsao <- predict(modelo,teste)
View(teste)
teste$cnpj_cpf <- NULL

```

Analisar resultados
```{r}
teste$Pre <- round(teste$Previsao/teste$`Valor Recebido`,2)
#teste$Pre <- teste$Prex-1
teste$Pre <- abs(teste$Pre)
R_1 <- summary(teste$Pre)
R_1
```
Analise de dados com Acuracia
```{r}

```

Organizar os dados em quantidade
```{r}
summary(tabela_despesa_publica2$`Valor Recebido`)
menos_de_dez_porcento <- quantile(tabela_despesa_publica2$`Valor Recebido`,0.90)

hist(tabela_despesa_publica2$`Valor Recebido`[tabela_despesa_publica2$`Valor Recebido`< menos_de_dez_porcento],xlab="Valores menores que 10%",breaks=10,labels=T)

```

Media de valores summary
```{r}
tabela_despesa_publica2$`Valor Recebido` %>% mean
summary(tabela_despesa_publica2$`Valor Recebido`)
```
